# Generated by Django 3.1.4 on 2020-12-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the user should be treated as active. Unselect this instead of deleting accounts', verbose_name='active'),
        ),
    ]
